# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20170803_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='page_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, editable=False),
        ),
    ]
