# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-07 21:42
from __future__ import unicode_literals

from django.db import migrations, models

from ..utils.comicapi.issuestring import IssueString


def add_issue_number_data(apps, schema_editor):

    Issue = apps.get_model('comics', 'Issue')
    query = Issue.objects.all()
    for issue in query:
        new_number = IssueString(issue.number).asString(pad=3)
        issue.number = new_number
        issue.save()


def remove_issue_number_data(apps, schema_editor):

    Issue = apps.get_model('comics', 'Issue')
    Issue.objects.update(number='')


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_issue_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.CharField(max_length=25, verbose_name='Issue number'),
        ),
        migrations.RunPython(
            add_issue_number_data,
            reverse_code=remove_issue_number_data
        ),
    ]
