# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify

SLUG_LENGTH = 200


def add_slug_data(apps, schema_editor):
    Series = apps.get_model(
        'comics', 'Series')
    query = Series.objects.all()
    for series in query:
        if series.year is not None:
            n = (series.name + ' ' + str(series.year))
        else:
            n = series.name
        new_slug = slugify(n)
        series.slug = new_slug
        series.save()


def remove_slug_data(apps, schema_editor):
    Series = apps.get_model(
        'comics', 'Series')
    Series.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_publisher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH,
                default=''),
        ),
        migrations.RunPython(
            add_slug_data,
            reverse_code=remove_slug_data
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH),
        ),
    ]
