# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify

SLUG_LENGTH = 200


def add_slug_data(apps, schema_editor):
    Creator = apps.get_model(
        'comics', 'Creator')
    query = Creator.objects.all()
    for creator in query:
        new_slug = slugify(creator.name)
        creator.slug = new_slug
        creator.save()


def remove_slug_data(apps, schema_editor):
    Creator = apps.get_model(
        'comics', 'Creator')
    Creator.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_series_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH,
                default=''),
        ),
        migrations.RunPython(
            add_slug_data,
            reverse_code=remove_slug_data
        ),
        migrations.AlterField(
            model_name='creator',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH),
        ),
    ]
