# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify

SLUG_LENGTH = 200


def add_slug_data(apps, schema_editor):
    Character = apps.get_model('comics', 'Character')
    query = Character.objects.all()
    for character in query:
        new_slug = slugify(character.name)
        character.slug = new_slug
        character.save()


def remove_slug_data(apps, schema_editor):
    Character = apps.get_model('comics', 'Character')
    Character.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH,
                default=''),
        ),
        migrations.RunPython(
            add_slug_data,
            reverse_code=remove_slug_data
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH),
        ),
    ]
