# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify

SLUG_LENGTH = 200


def add_slug_data(apps, schema_editor):
    Arc = apps.get_model('comics', 'Arc')
    query = Arc.objects.all()
    for arc in query:
        new_slug = slugify(arc.name)
        arc.slug = new_slug
        arc.save()


def remove_slug_data(apps, schema_editor):
    Arc = apps.get_model('comics', 'Arc')
    Arc.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0010_character_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH,
                default=''),
        ),
        migrations.RunPython(
            add_slug_data,
            reverse_code=remove_slug_data
        ),
        migrations.AlterField(
            model_name='arc',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH),
        ),
    ]
